In [8]:
import numpy as np

In [9]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
a.shape#tuple mentioning size of each dimension

(3, 5)

In [11]:
a.ndim#no of dimensions in an array

2

In [12]:
a.dtype.name#data type name

'int64'

In [14]:
a.itemsize#size of each element

8

In [15]:
a.size#no of elements in the array

15

In [16]:
type(a)

numpy.ndarray

In [17]:
b = np.array([6,7,8])
print(b)

[6 7 8]


In [18]:
type(b)

numpy.ndarray

**Array Creation**

In [19]:
b.dtype

dtype('int64')

In [21]:
c = np.array([(1,2),(3,4)]) #2d array
c

array([[1, 2],
       [3, 4]])

In [23]:
d = np.array([(1,2),(3,4)], dtype=complex)#2d array with data type declared
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
#creating arrays of 0s and 1s when the array has to be defined without knowing the elements
Z = np.zeros((2,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
O = np.ones((2,3,4),dtype=np.int16)

In [27]:
O

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
#empty array filled with random values which can be changed later
E = np.empty((3,3))
E

array([[0.00000000e+000, 0.00000000e+000, 2.59305228e-306],
       [2.42092166e-322, 4.66658003e-310, 6.90740491e-310],
       [0.00000000e+000, 0.00000000e+000, 3.95252517e-322]])

In [36]:
#function used to display an array as a range of values
R = np.arange(2,12,2)
R

array([ 2,  4,  6,  8, 10])

In [37]:
from numpy import pi
np.linspace(0,2,9) #9 numbers displayed from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [41]:
x = np.linspace(0,2*pi,100)
print(x)
f = np.sin(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [40]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

**Printing Arrays**

In [42]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [44]:
import sys

In [45]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [49]:
np.set_printoptions(threshold=None)

**Basic Operartions**

In [52]:
#Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
a = np.array([20,30,40,50])
b = np.arange(4)
c = a-b
c

array([20, 29, 38, 47])

In [53]:
b**2

array([0, 1, 4, 9])

In [55]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [56]:
a<30

array([ True, False, False, False])

In [57]:
a*b

array([  0,  30,  80, 150])

In [58]:
a@b

260

In [63]:
A = np.array([[1,2],[3,4]])
print(A)
B = np.array([[1,3],[5,7]])
print(B)

[[1 2]
 [3 4]]
[[1 3]
 [5 7]]


In [64]:
A*B #elementwise multiplication

array([[ 1,  6],
       [15, 28]])

In [65]:
A@B #matrix multiplication

array([[11, 17],
       [23, 37]])

In [101]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))

In [102]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [103]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [104]:
a*=3

In [105]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [106]:
b+=a

In [107]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [108]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [109]:
b.dtype

dtype('float64')

In [110]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [111]:
d = np.exp(c*1j)

In [112]:
d

array([ 0.40808206+0.91294525j, -0.74805753-0.66363388j,
        0.95507364+0.29636858j, -0.99233547+0.12357312j])

In [113]:
d.dtype

dtype('complex128')

In [117]:
a = rg.random((2,3))
print(a)
sum(a)

[[0.32973172 0.7884287  0.30319483]
 [0.45349789 0.1340417  0.40311299]]


array([0.78322961, 0.9224704 , 0.70630782])

In [119]:
a.sum()

2.412007822394087

In [121]:
a.min()

0.13404169724716475

In [122]:
a.max()

0.7884287034284043

In [123]:
a.sum(axis=0)

array([0.78322961, 0.9224704 , 0.70630782])

In [124]:
a.sum(axis=1)

array([1.42135525, 0.99065257])

In [125]:
b = np.arange(12).reshape(3,4)

In [126]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

**Universal Functions**


NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [127]:
B = np.arange(3)
B

array([0, 1, 2])

In [128]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [129]:
np.sin(B)

array([0.        , 0.84147098, 0.90929743])

In [130]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [132]:
A = np.array([3,4,5])
np.add(A,B)

array([3, 5, 7])

**Indexing, Slicing and Iterating**

In [134]:
a = np.arange(10)

In [135]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a[2]

2

In [137]:
a[3:9]

array([3, 4, 5, 6, 7, 8])

In [138]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [139]:
a[-1:]

array([9])

In [140]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [141]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [144]:
a = np.arange(10)**2

In [145]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [146]:
for i in a:
    print(i)

0
1
4
9
16
25
36
49
64
81


In [148]:
def f(x,y):
    return  10*x+y

In [150]:
b = np.fromfunction(f,(5,4),dtype=int)

In [151]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [152]:
b[2,3]

23

In [153]:
b[:1]

array([[0, 1, 2, 3]])

In [154]:
b[2:]

array([[20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [155]:
b[:2,:2]

array([[ 0,  1],
       [10, 11]])

In [158]:
b[-1]

array([40, 41, 42, 43])

In [159]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [160]:
c.shape

(2, 2, 3)

In [164]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [165]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [166]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [167]:
for element in b:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [169]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


**Shape Manipulation**

In [174]:
a = np.floor(10*rg.random((3,4)))

In [175]:
a

array([[5., 2., 8., 5.],
       [5., 7., 1., 8.],
       [6., 7., 1., 8.]])

In [176]:
a.shape

(3, 4)

In [177]:
a.ravel() #returns the array, flattened

array([5., 2., 8., 5., 5., 7., 1., 8., 6., 7., 1., 8.])

In [179]:
a.reshape((6,2)) #returns the array with a modified shape

array([[5., 2.],
       [8., 5.],
       [5., 7.],
       [1., 8.],
       [6., 7.],
       [1., 8.]])

In [181]:
a.T #returns the array transposed

array([[5., 5., 6.],
       [2., 7., 7.],
       [8., 1., 1.],
       [5., 8., 8.]])

In [182]:
a.T.shape

(4, 3)

**Stacking together different arrays**

In [187]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))

In [188]:
a

array([[6., 7.],
       [8., 2.]])

In [189]:
b

array([[2., 6.],
       [8., 9.]])

In [191]:
np.vstack((a,b)) #vertically stacking 2 arrays

array([[6., 7.],
       [8., 2.],
       [2., 6.],
       [8., 9.]])

In [193]:
np.hstack((a,b)) #horizantally stacking 2 arrays

array([[6., 7., 2., 6.],
       [8., 2., 8., 9.]])

In [194]:
from numpy import newaxis
np.column_stack((a,b))

array([[6., 7., 2., 6.],
       [8., 2., 8., 9.]])

In [195]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [196]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [197]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [198]:
a[:,newaxis]

array([[4.],
       [2.]])

In [199]:
b[:,newaxis]

array([[3.],
       [8.]])

In [200]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [201]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [202]:
a


array([4., 2.])

In [203]:
b

array([3., 8.])

In [204]:
np.row_stack((a,b))

array([[4., 2.],
       [3., 8.]])

In [205]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [206]:
a = np.array([[1,2,3],[5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [207]:
b = np.array([[10,9,8],[7,6,5]])
b

array([[10,  9,  8],
       [ 7,  6,  5]])

In [208]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10,  9,  8],
       [ 7,  6,  5]])

In [209]:
np.hstack((a,b))

array([[ 1,  2,  3, 10,  9,  8],
       [ 5,  6,  7,  7,  6,  5]])

In [210]:
np.row_stack((a,b))

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10,  9,  8],
       [ 7,  6,  5]])

In [213]:
np.column_stack((a.ravel(),b.ravel()))

array([[ 1, 10],
       [ 2,  9],
       [ 3,  8],
       [ 5,  7],
       [ 6,  6],
       [ 7,  5]])

In [214]:
np.row_stack((a.ravel(),b.ravel()))

array([[ 1,  2,  3,  5,  6,  7],
       [10,  9,  8,  7,  6,  5]])

In [215]:
    a = np.floor(10*rg.random((2,12)))
    a

array([[1., 4., 8., 4., 5., 0., 6., 9., 8., 8., 6., 2.],
       [7., 2., 8., 0., 8., 1., 3., 3., 6., 1., 3., 0.]])

In [216]:
#splitting the array into parts
np.hsplit(a,3)

[array([[1., 4., 8., 4.],
        [7., 2., 8., 0.]]),
 array([[5., 0., 6., 9.],
        [8., 1., 3., 3.]]),
 array([[8., 8., 6., 2.],
        [6., 1., 3., 0.]])]

In [218]:
np.vsplit(a,2)

[array([[1., 4., 8., 4., 5., 0., 6., 9., 8., 8., 6., 2.]]),
 array([[7., 2., 8., 0., 8., 1., 3., 3., 6., 1., 3., 0.]])]

In [223]:
a = np.array([1,2,4,5,6,7])
np.hsplit(a,2)

[array([1, 2, 4]), array([5, 6, 7])]

**Copies and Views**

In [224]:
a = np.array([1,2,3,4])
b =a
b is a

True

In [226]:
b[3] = 5

In [227]:
b

array([1, 2, 3, 5])

In [229]:
a # lists are mutable to any change in b will make change in a since a and b are 2 names of  same list

array([1, 2, 3, 5])

In [230]:
a

array([1, 2, 3, 5])

In [231]:
def f(x):
    print(id(x))

In [233]:
id(a)

139807229084336

In [234]:
f(a)

139807229084336


In [236]:
a.view()

array([1, 2, 3, 5])

In [237]:
c  = a.view()

In [238]:
c

array([1, 2, 3, 5])

In [239]:
c is a

False

In [240]:
c

array([1, 2, 3, 5])

In [241]:
c[0] = 7

In [242]:
c

array([7, 2, 3, 5])

In [243]:
a

array([7, 2, 3, 5])

In [244]:
c[0]= 9

In [245]:
c

array([9, 2, 3, 5])

In [246]:
a

array([9, 2, 3, 5])

In [247]:
c.base is a

True

In [248]:
c.base

array([9, 2, 3, 5])

In [249]:
c.base is a

True

In [250]:
c.flags.owndata

False

In [255]:
a = np.floor(10*rg.random((2,12)))

In [256]:
c = c.reshape((2, 6))

ValueError: cannot reshape array of size 4 into shape (2,6)

In [257]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
             [ 8,  9, 10, 11]])

In [258]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [259]:
c = c.reshape((2, 6))

ValueError: cannot reshape array of size 4 into shape (2,6)